version: "3"

services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  database:
    image: postgres:latest
    environment:
      DB_USERNAME: rusty
      DB_PASSWORD: evansochieng
      DB_NAME: livestock_tracing_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
