version: "3"

services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - database
    command: >
      bash -c "flask db upgrade && python seed.py && flask run --host 0.0.0.0 --port 5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  database:
    image: postgres:latest
    environment:
      DB_USERNAME: rusty
      DB_PASSWORD: evansochieng
      DB_NAME: livestock_tracing_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
