"""Create tables livestock, deforestation_areas

Revision ID: 308d10dfcb97
Revises: 
Create Date: 2023-07-15 12:42:40.629096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308d10dfcb97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deforestation_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livestocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('owner')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livestocks')
    op.drop_table('deforestation_areas')
    # ### end Alembic commands ###
