"""add name feature to deforested_areas table

Revision ID: fa68f27b89ee
Revises: 39ee27ba713e
Create Date: 2023-07-19 18:22:37.431740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa68f27b89ee'
down_revision = '39ee27ba713e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deforestation_areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_deforestation_areas', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deforestation_areas', schema=None) as batch_op:
        batch_op.drop_constraint('uq_deforestation_areas', type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
